# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: roboshop
#   region: us-east-1

# managedNodeGroups:
#   - name: spot
#     instanceType: m5.large
#     desiredCapacity: 3
#     spot: true


# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: my-cluster
#   region: us-east-1

# managedNodeGroups:
#   - name: spot
#     instanceTypes: ["m5.large", "m5a.large", "t3.large"]
#     desiredCapacity: 3
#     capacityType: SPOT


apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: us-east-1

managedNodeGroups:
  - name: spot
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    spot: true
